/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ISafeEngineInterface extends ethers.utils.Interface {
  functions: {
    "approveSAFEModification(address)": FunctionFragment;
    "coinBalance(address)": FunctionFragment;
    "transferInternalCoins(address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approveSAFEModification",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "coinBalance", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferInternalCoins",
    values: [string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveSAFEModification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coinBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferInternalCoins",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISafeEngine extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISafeEngineInterface;

  functions: {
    approveSAFEModification(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "approveSAFEModification(address)"(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    coinBalance(src: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "coinBalance(address)"(
      src: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferInternalCoins(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferInternalCoins(address,address,uint256)"(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  approveSAFEModification(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "approveSAFEModification(address)"(
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  coinBalance(src: string, overrides?: CallOverrides): Promise<BigNumber>;

  "coinBalance(address)"(
    src: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferInternalCoins(
    src: string,
    dst: string,
    rad: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferInternalCoins(address,address,uint256)"(
    src: string,
    dst: string,
    rad: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveSAFEModification(
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "approveSAFEModification(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    coinBalance(src: string, overrides?: CallOverrides): Promise<BigNumber>;

    "coinBalance(address)"(
      src: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferInternalCoins(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferInternalCoins(address,address,uint256)"(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveSAFEModification(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "approveSAFEModification(address)"(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    coinBalance(src: string, overrides?: CallOverrides): Promise<BigNumber>;

    "coinBalance(address)"(
      src: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferInternalCoins(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferInternalCoins(address,address,uint256)"(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveSAFEModification(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "approveSAFEModification(address)"(
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    coinBalance(
      src: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "coinBalance(address)"(
      src: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferInternalCoins(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferInternalCoins(address,address,uint256)"(
      src: string,
      dst: string,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
